;	TITLE	'bong`
;	Scott Baker, www.smbaker.com
;
; 	Plays the famous boot up music.
;

	EXTRN	COPEN
	EXTRN	ZSOUT
	EXTRN	EXIT
	EXTRN	PLAY
	EXTRN 	CSGNIT
	EXTRN	CSGMUT

	EXTRN	NC3
	EXTRN	NC3S
	EXTRN	ND3F
	EXTRN 	ND3
	EXTRN	ND3S
	EXTRN	NE3F
	EXTRN	NE3
	EXTRN	NF3
	EXTRN	NF3S
	EXTRN	NG3F
	EXTRN	NG3
	EXTRN	NG3S
	EXTRN	NA3F
	EXTRN	NA3
	EXTRN	NA3S
	EXTRN	NB3F
	EXTRN	NB3
	EXTRN	NC4
	EXTRN	NC4S
	EXTRN	ND4F
	EXTRN	ND4
	EXTRN	ND4S
	EXTRN	NE4F
	EXTRN	NE4
	EXTRN	NF4
	EXTRN	NF4S
	EXTRN	NG4F
	EXTRN	NG4
	EXTRN	NG4S
	EXTRN	NA4F
	EXTRN	NA4
	EXTRN	NA4S
	EXTRN	NB4F
	EXTRN	NB4
	EXTRN	NC5
	EXTRN	NC5S
	EXTRN	ND5F
	EXTRN	ND5

	EXTRN	NOTE16
	EXTRN	NOTE8
	EXTRN	NOTE4
	EXTRN	NOTE2
	EXTRN 	SIL

	EXTRN	ATTACH

	STKLN	100H				; Size of stack segment

	CSEG

ORIG:	NOP					; Some NOPs makes it easier for the disassembler to sync
	NOP
	NOP
	LXI	SP,STACK			; Setup initial stack
	CALL	COPEN				; Open the console
	LXI	D, HELLO			; Load Hello String
	CALL	ZSOUT				; Print string

	CALL	ATTACH				; Attach multimodule row 1

	CALL	CSGNIT				; silence and unmute

	LXI	D, BONGNT
	CALL	PLAY

	CALL	CSGMUT

	CALL	EXIT				; Exit to ISIS

HELLO:	DB	'Bong!', 0DH, 0AH, 0

BONGNT:	DW	ND5F, NOTE16, SIL, NOTE8, ND4F, NOTE16
	DW	NG4F, NOTE16, ND4F, NOTE16, NA4F, NOTE16, 0, 0

	END	ORIG
